name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
     
      - name: 'Create env file'
        run: |
             touch .service_account
             echo ${SERVICE_ACCOUNT}  >> .service_account
        shell: bash
        env:
          SERVICE_ACCOUNT: ${{secrets.GOOGLE_SERVICE_ACCOUNT}}
      
      # - name: 'Create env file'
      #   run: |
      #     touch service_account
      #     echo ${{ secrets.GOOGLE_SERVICE_ACCOUNT }} | base64 --decode > .service_account
         
      - name: Test
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          GOOGLE_PROJECT_ID: .service_account
          GOOGLE_PROJECT_LOCATION: US
        run: make test GOTEST_FLAGS="-v -count=1"
