name: lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4.0.0
        with:
          version: v1.42.1
